git clone https://github.com/Talend/studio.git
git clone https://github.com/Talend/components.git
git clone https://github.com/Talend/components-ee.git
git clone https://github.com/Talend/connectors-se.git
git clone https://github.com/Talend/connectors-ee.git
git clone https://github.com/Talend/cloud-components.git
git clone https://github.com/Talend/talend-sap-api.git
git clone https://github.com/Talend/tsap-rfc-server.git
git clone https://github.com/Talend/connectors-lib-se.git
git clone https://github.com/Talend/connectors-lib-ee.git